title: Categories
modelClass: Shohabbos\RestaurantMenu\Models\Category
list: $/shohabbos/restaurantmenu/models/category/columns.yaml
recordUrl: 'shohabbos/restaurantmenu/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
